-- Enable automatic tuning on an individual database
ALTER DATABASE current SET AUTOMATIC_TUNING (FORCE_PLAN= ON);
ALTER DATABASE current SET AUTOMATIC_TUNING (CREATE_INDEX = ON);
ALTER DATABASE current SET AUTOMATIC_TUNING (DROP_INDEX = ON);